# Generated by Django 5.0.6 on 2024-05-27 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traidingnet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traidingnet.contacts', verbose_name='Контакты'),
        ),
    ]
