# Generated by Django 5.0.6 on 2024-05-31 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traidingnet', '0004_contacts_create_user_product_create_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['company_name'], 'verbose_name': 'Поставщик', 'verbose_name_plural': 'Поставщики'},
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='sup_name',
            new_name='company_name',
        ),
    ]
