# Generated by Django 5.0.6 on 2024-05-31 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traidingnet', '0005_alter_supplier_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='supplier_type',
            new_name='seller_type',
        ),
    ]
